import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import fs from "fs";
import path from "path";
import { spawn } from "child_process";

/**
 * Create a stdio-based MCP server
 *
 * @param {Object} config - Configuration for the stdio server
 * @param {string} config.name - The name of the server
 * @param {string} config.command - The command to execute
 * @param {string[]} config.args - The arguments to pass to the command
 * @param {Object} config.options - Options for child_process.spawn
 * @param {string} [config.description] - Description of the server
 * @param {string} [config.authType='none'] - Authentication type
 * @returns {Promise<Object>} The created server object
 */
export async function createStdioServer(config) {
  const {
    name,
    command,
    args = [],
    options = { shell: true, cwd: process.cwd() },
    description,
    authType = "none",
    env,
    debug = false,
  } = config;

  const serverName = name;

  console.log(`Creating ${serverName}: ${command} ${args.join(" ")}`);

  // Create logs directory if it doesn't exist
  const logsDir = path.join(process.cwd(), "logs");
  if (!fs.existsSync(logsDir)) {
    fs.mkdirSync(logsDir, { recursive: true });
  }

  // Create log file paths
  const logFile = path.join(logsDir, `${serverName}.log`);
  const errorLogFile = path.join(logsDir, `${serverName}.error.log`);

  if (!debug) {
    console.log(`${serverName}: Logs will be written to ${logFile}`);
  }

  // For npx commands, add -y to make it non-interactive
  let finalArgs = args;
  if (command === "npx") {
    finalArgs = ["-y", ...args];
  }

  // Create the transport with proper stdio isolation
  const transport = new StdioClientTransport({
    command: command,
    args: finalArgs,
    stderr: "pipe", // Force stderr to be piped instead of inherited
    env: env ? { ...process.env, ...env } : undefined,
    ...options,
  });

  // Create the MCP client
  const mcpClient = new Client(
    {
      name: "toolbelt-bridge",
      version: "1.0.0", // You may want to get this from package.json
    },
    {
      capabilities: {
        prompts: {},
        resources: {},
        tools: {},
      },
    }
  );

  try {
    // Connect to the server via the client
    await mcpClient.connect(transport);
    console.log(`${serverName}: Connected via stdio`);
  } catch (error) {
    console.error(`${serverName}: Connection failed - ${error.message}`);
    throw error;
  }

  // Get the process after connecting - try accessing private property
  const serverProcess = transport.process || transport._process;

  // Add handlers for logging - redirect to log files
  if (serverProcess && serverProcess.stdout) {
    serverProcess.stdout.on("data", (data) => {
      const output = data.toString().trim();
      if (output) {
        // Always log to file
        const timestamp = new Date().toISOString();
        try {
          fs.appendFileSync(logFile, `[${timestamp}] ${output}\n`);
        } catch (error) {
          console.error(
            `Failed to write to log file ${logFile}: ${error.message}`
          );
        }

        // Only show in console if debug mode is enabled
        if (debug) {
          console.log(`${serverName}: ${output}`);
        }
      }
    });
  }

  if (serverProcess && serverProcess.stderr) {
    serverProcess.stderr.on("data", (data) => {
      const output = data.toString().trim();
      if (output) {
        // Log stderr to error file only
        const timestamp = new Date().toISOString();
        fs.appendFileSync(errorLogFile, `[${timestamp}] ${output}\n`);

        // Only show errors in console if debug mode is enabled
        if (debug) {
          console.error(`${serverName}: ${output}`);
        }
      }
    });
  }

  // Try to list tools immediately to check the connection
  let toolsList = [];
  try {
    toolsList = await mcpClient.listTools();
    const toolCount = Array.isArray(toolsList)
      ? toolsList.length
      : toolsList.tools
        ? toolsList.tools.length
        : 0;
    console.log(`${serverName}: ${toolCount} tools available`);
  } catch (toolError) {
    console.log(
      `${serverName}: Could not list tools yet - ${toolError.message}`
    );
  }

  // Extract tools from toolsList safely
  const extractedTools = Array.isArray(toolsList)
    ? toolsList.map((tool) =>
        typeof tool === "string" ? tool : tool.name || String(tool)
      )
    : toolsList.tools
      ? toolsList.tools.map((tool) =>
          typeof tool === "string" ? tool : tool.name || String(tool)
        )
      : [];

  // Create the server object
  const server = {
    name: serverName,
    // id will be generated by registerServer() using stable connection ID
    description: description || `MCP server for ${serverName} (stdio)`,
    authType,
    isCodedServer: true,
    tools: extractedTools,
    hasPreFetchedTools: true,
    client: mcpClient,
    process: serverProcess,

    // Connect to the server
    connect: async (bridgeTransport) => {
      // Create a sendRequest function and attach it to the transport
      bridgeTransport.sendRequest = async (request) => {
        try {
          // Convert the bridge request format to MCP client format
          let result;

          if (
            request.method === "tools/list" ||
            request.type === "list_tools"
          ) {
            result = await mcpClient.listTools();
            return { tools: result };
          } else if (request.method && request.method.startsWith("tools/")) {
            // Handle tool call
            const toolName = request.method.split("/")[1];
            result = await mcpClient.callTool({
              name: toolName,
              arguments: request.params || {},
            });
            return { result };
          } else if (request.type === "call_tool") {
            result = await mcpClient.callTool({
              name: request.name,
              arguments: request.arguments || {},
            });
            return { result };
          } else {
            throw new Error(
              `Unsupported request type: ${request.method || request.type}`
            );
          }
        } catch (error) {
          console.error(`${serverName} request failed: ${error.message}`);
          throw error;
        }
      };

      // Set up onRequest handler as well for incoming requests
      bridgeTransport.onRequest = async (request) => {
        return bridgeTransport.sendRequest(request);
      };

      return bridgeTransport;
    },

    // Disconnect from the server
    disconnect: async () => {
      try {
        await mcpClient.disconnect();
        console.log(`${serverName}: Disconnected`);

        if (serverProcess && !serverProcess.killed) {
          serverProcess.kill();
          console.log(`${serverName}: Process terminated`);
        }
      } catch (error) {
        console.error(`${serverName}: Disconnect error - ${error.message}`);
      }
    },
  };

  return server;
}

/**
 * Start a stdio service using the given configuration
 *
 * @param {Object} config - The service configuration
 * @returns {Promise<Object>} The created server
 */
export async function startStdioService(config) {
  try {
    // Create the stdio server
    const server = await createStdioServer(config);

    // Add process exit handler
    if (server.process) {
      server.process.on("exit", (code) => {
        console.log(
          `Server process for ${server.name} exited with code ${code}`
        );
      });

      server.process.on("error", (error) => {
        console.error(
          `Error in server process for ${server.name}: ${error.message}`
        );
      });
    }

    return server;
  } catch (error) {
    console.error(`Failed to start stdio service: ${error.message}`);
    throw error;
  }
}
